apiVersion: 1

datasources:
  - name: StressTest PostgreSQL
    type: postgres
    uid: stresstest-postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
    editable: true
